version: '3.8'

services:
  # base url: http://nginx_recipes:80
  # make sure when adding api key scope is "read write"
  db_recipes:
    container_name: db_recipes
    restart: always
    image: postgres:16-alpine
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    env_file:
      - ./tandoor.env
    networks:
      default:

  web_recipes:
    container_name: web_recipes
    restart: always
    image: vabene1111/recipes
    env_file:
      - ./tandoor.env
    volumes:
      - staticfiles:/opt/recipes/staticfiles
      # Do not make this a bind mount, see https://docs.tandoor.dev/install/docker/#volumes-vs-bind-mounts
      - nginx_config:/opt/recipes/nginx/conf.d
      - ./mediafiles:/opt/recipes/mediafiles
    depends_on:
      - db_recipes
    networks:
      default:

  nginx_recipes:
    container_name: nginx_recipes
    image: nginx:mainline-alpine
    restart: always
    ports:
      - 80:80
    env_file:
      - ./tandoor.env
    depends_on:
      - web_recipes
    volumes:
      # Mount our custom nginx config
      - nginx_config:/etc/nginx/conf.d:ro
      - staticfiles:/static:ro
      - ./mediafiles:/media:ro
    networks:
      skylite-ux_devcontainer_default:
      default:

volumes:
  nginx_config:
  staticfiles:
  
networks:
  default:
  skylite-ux_devcontainer_default:
    external: true