version: "3.8"

services:
  # base url: http://nginx_recipes:80
  # make sure when adding api key scope is "read write"
  db_recipes:
    container_name: db_recipes
    restart: always
    image: postgres:16-alpine
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    env_file:
      - ./tandoor.env
    networks:
      default:

  web_recipes:
    container_name: web_recipes
    restart: always
    image: vabene1111/recipes
    env_file:
      - ./tandoor.env
    volumes:
      - staticfiles:/opt/recipes/staticfiles
      # Do not make this a bind mount, see https://docs.tandoor.dev/install/docker/#volumes-vs-bind-mounts
      - nginx_config:/opt/recipes/nginx/conf.d
      - ./mediafiles:/opt/recipes/mediafiles
    depends_on:
      - db_recipes
    networks:
      default:

  nginx_recipes:
    container_name: nginx_recipes
    image: nginx:mainline-alpine
    restart: always
    ports:
      - 80:80
    env_file:
      - ./tandoor.env
    depends_on:
      - web_recipes
    volumes:
      # Do not make this a bind mount, see https://docs.tandoor.dev/install/docker/#volumes-vs-bind-mounts
      - nginx_config:/etc/nginx/conf.d:ro
      - staticfiles:/static:ro
      - ./mediafiles:/media:ro
      # Mount our local conf for copying
      - ./nginx/conf.d:/tmp/nginx/conf.d:ro
    # Copy the custom conf to the container
    command: >
      sh -c "
        cp /tmp/nginx/conf.d/Recipes.conf /etc/nginx/conf.d/ &&
        cp -r /tmp/nginx/conf.d/errorpages /etc/nginx/conf.d/ 2>/dev/null || true &&
        nginx -g 'daemon off;'
      "
    networks:
      skylite-ux_devcontainer_default:
      default:

volumes:
  postgresql_data:
  nginx_config:
  staticfiles:

networks:
  default:
  skylite-ux_devcontainer_default:
    external: true
